service: aws-node-project
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2
  

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
